### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by Samuel-Duque** [Samuel-Duque/Tracker#3]
- [x] Design componente card.
- [x] Design componente card (noOwner).
- [x] Tela detalhe da música.
- [x] Home - Sessão recém lançadas e mais ouvidas
- [x] Perfil do user
- [x] Tela de músicas
- [x] Perfil do artista

**Comment by ZeAndradee** [comment]
### **DarkMode**

- [ ] Cards
- [ ] BottomInfoCards
- [ ] HomeBackground - Color Fix
- [ ] Profile
